### ISSUE TITLE
prioritize extension key

### ISSUE THREAD

**Issue by Starraider** [TYPO3-Documentation/t3docs-search-indexer#15]
If I search for a popular extension like the _bootstrap_package_ for example, the search result shows dozens of other extensions in the first place just because they are related to the extension. But instead the searched extension should appear at the first position. Maybe you could give the extension key a higher priority in the search? Or there could be a filter where you can limit the search to the extension key? Otherwise, it would be hard to find the manual of a popular extension.

**Comment by tmotyl** [comment]
@gr0 this will also be some kind of boosting?

**Comment by gr0** [comment]
Yes, boosting on URL field would potentially solve that, but the URL needs to be parsed accordingly. For example with the use of https://www.elastic.co/guide/en/elasticsearch/reference/7.13/analysis-simplepatternsplit-tokenizer.html, which is the simplest approach. That way documents with URL like `bk2k/bootstrap_package` could be boosted as the URL would be tokenized into `bk2k` and `bootstrap_package` and because the query is `bootstrap_package` it would work. Of course if this is what we are looking for.

**Comment by tmotyl** [comment]
Note:
Field `manual_title` contains an extension vendor and extension name. eg. bk2k/bootstrap-package
Right now it's configured as 
```
manual_type:
  type: keyword
```
This field is not used right now in search query.

**Comment by gr0** [comment]
That would have to be adjusted, data re-indexed and can be used only for boosting.

**Comment by tmotyl** [comment]
just adding `manual_title` to query is not enough. This query doesn't yeld results:
```
{
  "query": {
    "function_score": {
      "query": {
        "bool": {
          "must": [
            {
              "query_string": {
                "query": "bootstrap-package",
                "fields": [
                  "manual_title"
                ]
              }
            }
          ]
        }
      }
    }
  },
  "size": 10,
  "from": 0
}
```

Where this query does return results (as there is a exact match):
```
{
  "query": {
    "function_score": {
      "query": {
        "bool": {
          "must": [
            {
              "query_string": {
                "query": "bk2k\\/bootstrap-package",
                "fields": [
                  "manual_title"
                ]
              }
            }
          ]
        }
      }
    }
  },
  "size": 10,
  "from": 0
}
```

**Comment by tmotyl** [comment]
@gr0 do I get it right, that in order for tokenizer to work, we need another field than `manual_title`, as the `manual_title` is a keyword field (and we already are using it for filtering).
or is there better way around it?

**Comment by gr0** [comment]
Heh, I should have looked into the mappings. You can create `fields` object for the `manual_title` field and include a new field there that is analyzed. Just try to be consistent - usually the way people approach it is that the top level field, so the `manual_title` here would be searchable and it would have a `keywords` field inside it for filtering.

**Comment by tmotyl** [comment]
I've added the changes about manual_title to https://github.com/TYPO3-Documentation/t3docs-search-indexer/pull/32
Let's see how will it behave with all data on prod, hopefully, we will be able to close this issue then.

**Comment by tmotyl** [comment]
change was deployed, search for "bootstrap_package" yelds nice results
![image](https://user-images.githubusercontent.com/515397/152557312-caadbdfd-c1ea-4707-b8f2-c127e21289f3.png)
