### ISSUE TITLE
Highlight found matches

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/t3docs-search-indexer#16]
I guess it would be cool to highlight found matches in abstracts.
Search engines like duck duck go or google mark found matched in bold.

That allows easier scanning of results.

**Comment by tmotyl** [comment]
That would be possible, ES provides api for it https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html

**Comment by tmotyl** [comment]
Here are 3 examples how the highlighting could look like:
![image](https://user-images.githubusercontent.com/515397/122558174-11cb0680-d03e-11eb-84cd-ed2870ad45fd.png)

**Comment by tmotyl** [comment]
As a first step, I'm adding just the bold
