### ISSUE TITLE
Rank official manuals from supported TYPO3 versions higher

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/t3docs-search-indexer#18]
Assumption:
TYPO3 core manuals should be ranked higher than community manuals.
Example https://docs.typo3.org/search/search?q=typoscript shows extension manuals first, expected is to see typo3script reference first

Assumption:
Official Manuals from supported TYPO3 versions (11, 10, 9) should be ranked higher than one from not supported. 
Example query: "FLUIDTEMPLATE" shows older versions first.
![image](https://user-images.githubusercontent.com/515397/121146639-6c937f80-c840-11eb-8ed5-90f1d3cbd196.png)
Solutions:
1) boost supported TYPO3 versions
The challenge here is that right now we don't distinguish between extension version and TYPO3 version. So if we boost e.g. version 10, extensions which has versions higher than TYPO3 (e.g. 16.0) will have degraded results.
If there were means to get the TYPO3 version certain extension is compatible with we could have the boosting working nicely.
Alternatively, we could boost based on time,  if we knew when certain release was published (we only have the documentation rendering time right now).
2) Other solution is to to separate the version into 2 filters:
Core manual version and community extension version, and add boost only if the first one is in the range.
3) we could do a boosting based on 2 fileds - boost documents which has  version in certain range AND is a core manual

**Comment by gr0** [comment]
IMHO the simplest and cleanest solution will be to separate the version into the core version and extension version and then boost the core version for the officially supported TYPO3 versions. That should help in keeping the recent versions on top, they will just have to have proper boost.

**Comment by tmotyl** [comment]
@gr0  What about solution 3, would it be possible too? or too much hassle?

**Comment by gr0** [comment]
Third option is also possible, you can use a `function_score` query for that: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html. Maybe it would be even simpler, because it wouldn't require changed and splitting the versions into two.

**Comment by tmotyl** [comment]
@gr0 can you provide and example or at last a hint which score function type to use?
Thanks

**Comment by gr0** [comment]
Sure, I'll get back with the example as soon as I'm back from vacation, unless this is a high priority task.

**Comment by tmotyl** [comment]
Take your time :)

**Comment by gr0** [comment]
@tmotyl this should like more or less like this:

```
{
  "query": {
    "function_score": {
      "query": { 
        "term": {
          "name": "documentation"
        }
      },
      "functions": [
        {
          "filter": { 
            // query matching core manual pages
          },
          "weight": 5
        },
        {
          "filter": { 
            // query matching recent version
          },
          "weight": 5
        }
      ],
      "score_mode": "max",
      "boost_mode": "multiply"
    }
  }
}
```

We should match the documents that have the required version and that are from core manual and give them a boost. The `weight` may have to be adjusted depending on the data. I would suggest checking a few queries and see what boost will work and will not make the results bad.

**Comment by tmotyl** [comment]
Will this give boost only to documents witch meet both conditions (version and core manual)?

**Comment by gr0** [comment]
Yes - with one comment - the score_mode should be set to something like sum or maybe multiply. I used max in my example which will only take max score, and we want both.

**Comment by tmotyl** [comment]
deployed, see https://github.com/TYPO3-Documentation/t3docs-search-indexer/commit/597925c477c9bab2d71cec13e6c428e36060b88b
