### ISSUE TITLE
Prioritization

### ISSUE THREAD

**Issue by bmack** [TYPO3-Documentation/t3docs-search-indexer#22]
Hey all,

I searched for https://docs.typo3.org/search/search?q=getText and 7.6 is shown before the latest versions. Could we rank this different?

Also, would it be better to rank Core docs higher than extensions, when searching e.g. for "https://docs.typo3.org/search/search?q=datahandler" ?

**Comment by tmotyl** [comment]
https://github.com/TYPO3-Documentation/t3docs-search-indexer/issues/18
see ^^

**Comment by bmack** [comment]
Ha, you thought of everything already :D
