### ISSUE TITLE
Input value name "q" is in conflict with Sphinx code

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/t3docs-search-indexer#23]
Would it be a problem to use a different name for the searchinput variable?

At the moment it is "q". See for example: https://github.com/TYPO3-Documentation/t3docs-search-indexer/blob/main/templates/search/search.html.twig#L97

It seems to be in conflict with what Sphinx has in its files.

**Comment by tmotyl** [comment]
>  It seems to be in conflict with what Sphinx has in its files.

What do you mean?

changing variable name would require changes to the search code and also matomo snippets.

**Comment by tmotyl** [comment]
@marble ping

**Comment by marble** [comment]
@tmotyl pong - I received the ping. I'm planning to dive into it again and elaborate on the problem.

**Comment by tmotyl** [comment]
this will not matter any more once the new php rendering is out.
