### ISSUE TITLE
better relation to what has been found (esp. in changelog)

### ISSUE THREAD

**Issue by maddy2101** [TYPO3-Documentation/t3docs-search-indexer#29]
I put a search string into the specific search box when changelog is open. Pressing Enter starts the search.  The result list then contains a lot of items with the issue number displayed.
What I miss: the TYPO3 version this result item belongs to, like Changelog/7.2 Changes. I get this information, when I click one of the items, then the menu in left hand side bar reveals the relation. This would a very valuable information to have already in result list.

This is what it looks like right now, no chance to tell what version the items are related to
![Search — TYPO3 CMS Core ChangeLog master documentation](https://user-images.githubusercontent.com/1925287/143532935-9eab5c7f-ef6b-43ac-8724-8beeefbfa8d3.png)

**Comment by DavidBruchmann** [comment]
While the link itself certainly did expose the TYPO3 version already the current search results are displayed now nicely with labels for the branch, rspectively version 

![image](https://user-images.githubusercontent.com/999146/221097229-71af6aa0-197a-4f30-b3bf-96b855f3dc4d.png)

**Comment by soee** [comment]
Here, we might have a problem with the current implementation. I discussed this with @linawolf. 
Currently, we index snippets (sections from manuals, where a manual is a documentation page). The same snippet might exist in multiple manual versions, such as 9.5, 10.04, 11.0, etc. To avoid duplicates in the index, we store each snippet only once and assign multiple versions to it (these are stored in a single field).

Now, the idea was to also store the title of each snippet's page (manual) and render it on the search results list, especially if the snippet's headline is very short (like `TCA`). However, even though the same snippet might exist across multiple manual versions, the manual's title might differ. Thus, we can't be sure that a single stored manual title will be accurate for all versions.

**Comment by tmotyl** [comment]
As changelog doesn;t have different versions, there is no benefit of spliting them into snippets.
I think the easiest way would be to change indexing for snippets, to treat the whole changelog page as a one snippet.

**Comment by linawolf** [comment]
We do have a similar issue in the exceptions, see for example https://docs.typo3.org/search/search?scope=%2Fm%2Ftypo3%2Freference-exceptions%2Fmain%2Fen-us%2F&q=Solution
