### ISSUE TITLE
Boost on extension key direct match 

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/t3docs-search-indexer#35]
If a search value is a match on the extension key, there should be a boost, e.g search for "news"

**Comment by DavidBruchmann** [comment]
@tmotyl @tomasnorre @paulfcdd I guess you could tell something about it, or even adjust it? Else, whom to ask?

**Comment by tmotyl** [comment]
isn't this already solved?

**Comment by linawolf** [comment]
looks good to me
