### ISSUE TITLE
No results for "FlashMessageService"

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/t3docs-search-indexer#59]
When searching for "FlashMessageService", no results are found:
https://docs.typo3.org/search/search?q=FlashMessageService

The word appears in https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/FlashMessages/FlashMessagesApi.html which should be found and shown as result.

![2024-01-12 Auswahl_003](https://github.com/TYPO3-Documentation/t3docs-search-indexer/assets/59036/44bc15eb-0b7e-438f-9b0d-a7f975d8520b)

**Comment by soee** [comment]
@cweiske should work now, after latest changes in code and re-indexing data.

**Comment by cweiske** [comment]
Today two changelog pages are found, but not the most relevant API page.

**Comment by linawolf** [comment]
The word "FlashMessageService" is only mentioned within a code block which is rated quite low in searches. I tried improving this by mentioning it in the text as well. 

@soee do we currently ignore code blocks completely? It almost seems like that?
