### ISSUE TITLE
No results for changelog ID "78192"

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/t3docs-search-indexer#61]
When searching for a changelog ID `78192` or `#78192` I get no results:
https://docs.typo3.org/search/search?q=78192

My expectation is to get a link to the changelog entry at
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/8.6/Feature-78192-RefactorClickMenuContextMenu.html

**Comment by soee** [comment]
@cweiske it should work now. Yesterday new version was deployed and changes related to changelog were there.

**Comment by linawolf** [comment]
Confirmed, both work now
