### ISSUE TITLE
Bad results for "f:image" 

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/t3docs-search-indexer#63]
When searching for `f:image` https://docs.typo3.org/search/search?q=f%3Aimage I expect to get "Fluid ViewHelper Reference > f:image" as result, but that is not listed there:
https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Image.html

**Comment by linawolf** [comment]
@soee It seems like indeed the [Fluid ViewHelper Reference](https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/Index.html) is not indexed at all. Can you check this?

**Comment by linawolf** [comment]
The Viewhelper reference is now found, however we have to improve the content so that The image viewhelper can be found by ` f:image `
