### ISSUE TITLE
Search field missing in main mask documentation

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/t3docs-search-indexer#73]
https://docs.typo3.org/p/mask/mask/main/en-us/Index.html does not show the project-specific search field anymore.
The earlier releases still have it.

## main
![2024-03-14 mask search main](https://github.com/TYPO3-Documentation/t3docs-search-indexer/assets/59036/f8443a07-2f6d-4801-ae6d-f9780518efbb)

## 8.3
![2024-03-14 mask search 8 3](https://github.com/TYPO3-Documentation/t3docs-search-indexer/assets/59036/e5e41e35-33b7-4e42-87fe-131c70a37419)

**Comment by linawolf** [comment]
Should be solved by https://github.com/TYPO3-Documentation/t3docs-search-indexer/pull/75

After triggering a rerendering users can now use the drop down:
![image](https://github.com/TYPO3-Documentation/t3docs-search-indexer/assets/48202465/b305f4ff-fda2-4f3d-b946-a112a81ac126)
