### ISSUE TITLE
404 result link when searching for "changelog"

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/t3docs-search-indexer#74]
When searching for "changelog", the 2nd result is
> [ChangeLog main](https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/Master.html#changelog-main) typo3/cms-core System extension

This page leads to a 404 Not Found.

https://docs.typo3.org/search/search?q=changelog

**Comment by linawolf** [comment]
@soee please schedule to solve this.

Changelog links look like this:

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4/Deprecation-100639-DeprecateAbstractPlugin.html

It must always be in "/c/typo3/cms-core/main/en-us/" all other versions must be ignored. They sometimes get rendered by mistake and we delete them again. This leads to these 404 errors.

We should exclude all other versions of the changelog except main. Also we should trigger deleting indexes of those that got indexed.

Oh and when searching for Changelog the start page of the changelog should be first, I feel?

**Comment by soee** [comment]
@linawolf as mentioned on the Slack, most likely this there was a `c/typo3/cms-core/11.5/en-us/Master.html` file which was not a part of the changelog (was not inside the Changelog folder). The importer indexed it as a core extension manual.

Probably this file was removed later on and the index was not updated, so the snippet for removed file still exists inside index and shows up on search results list, pointing to not existing file.
