### ISSUE TITLE
Exceptions manual not indexed

### ISSUE THREAD

**Issue by fsuter** [TYPO3-Documentation/t3docs-search-indexer#79]
The manual listing all the TYPO3 exception codes (https://docs.typo3.org/typo3cms/exceptions/main/en-us/Index.html) is not indexed in the general documentation search. Hence exception codes cannot be searched for using the global search.

**Comment by linawolf** [comment]
Thank you, we are at it

**Comment by linawolf** [comment]
I switched the exceptions manual to the new rendering and it is available in the search now, see for example https://docs.typo3.org/search/search?scope=%2Fm%2Ftypo3%2Freference-exceptions%2Fmain%2Fen-us%2F&q=1711797936

**Comment by fsuter** [comment]
Brilliant, thanks!
