### ISSUE TITLE
Do not index Changelog Index.html file

### ISSUE THREAD

**Issue by soee** [TYPO3-Documentation/t3docs-search-indexer#83]
The Changelog documentation for a given version might contain the `Index.html` file, which just lists the breaking changes, features, deprecations etc.  (please see for example: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5/Index.html#breaking-changes).

This content is not valuable for a user,  and often might not contain much of the data. To keep in the index what is really important and have valuable content, we should ignore the Changelog `Index.html` file for given version.

We can achieve this by using the dedicated metatag  `x-typo3-indexer` with value `noindex` inside this file (this has to be done when the documentation is rendered). This way the indexing application will ignore such file.

**Comment by linawolf** [comment]
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/84740

**Comment by tmotyl** [comment]
this is already fixed, right?
