### ISSUE TITLE
Searching for templateRootPaths in TSref returns no result. It is mentioned plenty of times

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-search-indexer#86]
https://docs.typo3.org/search/search?scope=%2Fm%2Ftypo3%2Fdocs-how-to-document%2Fmain%2Fen-us%2F&q=templateRootPaths

**Comment by tmotyl** [comment]
I believe the link you pasted is for the wrong documentation.
This works 
https://docs.typo3.org/search/search?scope=%2Fm%2Ftypo3%2Freference-typoscript%2Fmain%2Fen-us%2F&q=templateRootPaths

**Comment by linawolf** [comment]
woops
